config/routes.rb
Rails.application.routes.draw do
  
  mount Locomotive::Engine => '/locomotive', as: 'locomotive' # you can change the value of the path, by default set to "/locomotive"

  mount Locomotive::API.to_app => '/locomotive(/:site_handle)/api'

  mount Locomotive::Steam::Server.to_app => '/', anchor: false

  Locomotive::Engine.routes.draw do
    scope ':site_handle' do

    resources :twitter, path: 'twitter/:slug/entries'
      end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locomotive/twitter_controller.rb
require 'open-uri'
require 'json'
module Locomotive

  class TwitterController < Locomotive::ContentEntriesController

    def show
      authorize @content_entry
      begin
        # send("send_#{@content_entry.post_type}_tweet")
        send_offer_tweet
        flash[:success] = "Tweeted"
      rescue Exception => e
        flash[:error] = "Couldn't tweet: #{e.message}"
      end
      redirect_to(:back)
    end

    private

    def client
      creds = JSON.parse(File.read('config/twitter.json'))[Rails.env.to_s]
      Twitter::REST::Client.new do |config|
        config.consumer_key        = creds["consumer_key"]
        config.consumer_secret     = creds["consumer_secret"]
        config.access_token        = creds["access_token"]
        config.access_token_secret = creds["access_token_secret"]
      end
    end

    def send_offer_tweet
      offer = @content_entry
      url = Bitly.client.shorten("http://www.baratrip.es/ofertas/#{offer._slug}").short_url
      if offer.photos.size > 0
        photo = offer.photos[0]
        uri = URI.parse(photo.file.url)
        media = uri.open
        media.instance_eval("def original_filename; '#{File.basename(uri.path)}'; end")
        client.update_with_media("#{offer.title}. Visita #{url} #viajar #ofertas", File.new(media))
      else
        client.update("#{offer.title}. Visita #{url} #viajar #ofertas")
      end
    end

    def send_promocode_tweet
      if @content_entry.has_promocodes?
        promocode = @content_entry.promocodes.last
        url = Bitly.client.shorten("http://www.baratrip.es/descuentos/#{@content_entry._slug}").short_url
        if @content_entry.photos.size > 0
          photo = @content_entry.photos[0]
          uri = URI.parse(photo.file.url)
          media = uri.open
          media.instance_eval("def original_filename; '#{File.basename(uri.path)}'; end")
          client.update_with_media("#{promocode.title}. Visita #{url} #viajar #ofertas", File.new(media))
        else
          client.update("#{promocode.title}. Visita #{url} #viajar #ofertas")
        end
      else
        raise "No promocodes for this post"
      end
    end

    def send_post_tweet
      url = Bitly.client.shorten("http://www.baratrip.es/posts/#{@content_entry._slug}").short_url
      if @content_entry.photos.size > 0
        photo = @content_entry.photos[0]
        uri = URI.parse(photo.file.url)
        media = uri.open
        media.instance_eval("def original_filename; '#{File.basename(uri.path)}'; end")
        client.update_with_media("#{@content_entry.title}. Visita #{url} #viajar #ofertas", File.new(media))
      else
        client.update("#{@content_entry.title}. Visita #{url} #viajar #ofertas")
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoviajerosCms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locomotive/content_entries/_list.html.slim
- if empty_collection?(entries)

  br

  .alert.alert-warning
    == t('.no_items', url: new_content_entry_path(current_site, content_type.slug))

- else

  #entries-list class="row big-list #{'grouped' if content_type.groupable?} #{'sortable' if content_type.order_manually?}" data-sort-url=sort_content_entries_path(current_site, content_type.slug, :json)
    - entries.each do |entry|
      .item.col-md-12 data-id=entry._id
        - if content_type.order_manually?
          .draggable
            i.fa.fa-bars.draggable

        .text
          .item-label
            = entry_label(content_type, entry)
          .stamp
            == document_stamp(entry)

        .actions
          = link_to twitter_path(current_site, content_type.slug, entry), title: "tweet", class: 'tweet', data: { confirm: t('locomotive.messages.confirm') }, method: :get do
            i.fa.fa-twitter
          br
          = link_to content_entry_path(current_site, content_type.slug, entry), title: t(:delete, scope: 'simple_form.buttons.defaults.locomotive'), class: 'remove', data: { confirm: t('locomotive.messages.confirm') }, method: :delete do
            i.fa.fa-trash-o


- if entries.respond_to?(:current_page)
  .text-center
    = paginate entries, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-sm'